### ISSUE TITLE
SHA+HMAC is not "storing passwords securely"

### ISSUE THREAD

**Issue by migg24** [nodejsera/30daysofnode#1]
Please don't tell people using HMAC with SHA is a synonym for _storing passwords securely_. **It is not**.

There are algorithms specifically designed for storing passwords securely like _bcrypt_ or _argon2_. **Use them**.

The SHA algorithm is designed to calculate a hash of huge amounts of data as fast as possible. A salt can protect you from rainbow tables but not from brute forcing or dictionary attacks. 

Bcrypt and Argon2 are designed to be expensive and are adaptable to increasing computational power. 

If you don't change the encryption in your tutorials at least remove the sentence "Perform HMAC operation on password using crypto module of node.js for storing password securely." from day 13 and add a security warning that encrypting passwords with SHA is **unsafe** and should not be used in production systems, that it is only used for demonstration purpose or something.

**Comment by nodejsera** [comment]
hello,
We appreciate your concern and we have removed the content which beginners might misunderstood.
This will be visible on https://nodejsera.com within 30 mins.
Regards
Team Nodejsera

**Comment by migg24** [comment]
You did not add the warning but thanks for removing the sentence.

**Comment by nodejsera** [comment]
Hello,
Thanks for reaching out. We added the warning but due to some reasons we were not able to update the _live website_ yet. The changes will be visible within next **12** hours. 
We appreciate your concern.
Regards
Team Nodejsera
