### ISSUE TITLE
The 30 day of the example code is wrong, 

### ISSUE THREAD

**Issue by LinFengYnu** [nodejsera/30daysofnode#3]
such as router undefined, authorize_url misspelled.

**Comment by nodejsera** [comment]
Greetings,
Thanks for reaching out....
Please mention the article number and we will look into it.
regards,
Team nodejsera

**Comment by LinFengYnu** [comment]
number：30
url：https://www.nodejsera.com/nodejs-tutorial-day30-github-api-with-node.html
![image](https://user-images.githubusercontent.com/16188742/36539598-596fc6e8-1812-11e8-8b6a-948c3795ad16.png)

**Comment by nodejsera** [comment]
Greetings,
Thanks for sharing the details.
We will look into the matter.
Regards,
Team Nodejsera

**Comment by nodejsera** [comment]
Greetings,
The issues are resolved.
Please Feel free to check. 
Regards,
Team [Nodejsera](https://nodejsera.com)

**Comment by rogers9798** [comment]
the code is still not working
